[build]
  command = "vite build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# MOBILE-OPTIMIZED HEADERS
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # SIMPLIFIED CSP for mobile compatibility
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https: wss: data: blob:; img-src 'self' https: data: blob:; font-src 'self' data:; media-src 'self' blob:; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'self' https:; object-src 'none'; base-uri 'self';"
    
    # MOBILE FRAME SUPPORT - Remove X-Frame-Options to avoid conflicts
    # X-Frame-Options = "ALLOWALL"  # REMOVED - conflicts with CSP frame-ancestors
    
    # CORS for mobile
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    
    # Mobile-specific optimizations
    X-UA-Compatible = "IE=edge"
    Vary = "Accept-Encoding, User-Agent"
    
    # Viewport and mobile meta (these don't go in netlify.toml but should be in your HTML)
    # <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API function headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, x-farcaster-signature"
    Cache-Control = "no-cache"

# Farcaster well-known files
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    # SIMPLIFIED for mobile compatibility
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"
    
[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

# Handle OPTIONS requests for CORS preflight
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false
  conditions = {Method = ["OPTIONS"]}

# Specific redirects for common API patterns
[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/webhook"
  status = 200