[build]
  command = "vite build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Main headers for all routes - MOBILE OPTIMIZED
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # MOBILE-FRIENDLY CSP with complete Farcaster coverage
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://mainnet.base.org https://sepolia.base.org https://base-sepolia.g.alchemy.com https://base-sepolia.blockpi.network https://base-sepolia.public.blastapi.io https://rpc.ankr.com https://eth.llamarpc.com https://cloudflare-eth.com https://ethereum.publicnode.com https://api.pinata.cloud https://gateway.pinata.cloud https://ipfs.io https://dweb.link https://*.thirdweb.com https://embedded-wallet.thirdweb.com https://pay.thirdweb.com wss://*.thirdweb.com wss://sepolia.base.org wss://base-sepolia.g.alchemy.com https://*.walletconnect.org https://*.walletconnect.com wss://*.walletconnect.org wss://*.walletconnect.com https://explorer-api.walletconnect.com https://registry.walletconnect.com https://rpc.walletconnect.com https://relay.walletconnect.com wss://relay.walletconnect.com https://*.coinbase.com https://*.metamask.io https://metamask.io https://*.farcaster.xyz https://client.farcaster.xyz https://warpcast.com https://client.warpcast.com https://wrpcd.net https://*.wrpcd.net https://privy.farcaster.xyz https://privy.warpcast.com https://auth.privy.io https://*.rpc.privy.systems https://cloudflareinsights.com; img-src 'self' https://gateway.pinata.cloud https://*.pinata.cloud https://ipfs.io https://dweb.link https://*.thirdweb.com https://*.walletconnect.org https://*.walletconnect.com https://*.coinbase.com https://*.metamask.io https://metamask.io https://*.farcaster.xyz https://warpcast.com data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:; frame-src 'self' https://*.thirdweb.com https://*.walletconnect.org https://*.walletconnect.com https://*.coinbase.com https://*.metamask.io https://metamask.io; worker-src 'self' blob:; child-src 'self' blob:; frame-ancestors 'self' https://*.farcaster.xyz https://farcaster.xyz https://client.farcaster.xyz https://warpcast.com https://client.warpcast.com https://*.warpcast.com https://app.warpcast.com https://mobile.warpcast.com https://ios.warpcast.com https://android.warpcast.com https://frames.warpcast.com https://embed.warpcast.com https://fc-iframe.vercel.app https://frames.farcaster.xyz https://cast.farcaster.xyz https://frame.farcaster.xyz https://frames-v2.farcaster.xyz https://frames.warpcast.xyz file: capacitor: ionic: warpcast: farcaster:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "ALLOWALL"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    # Mobile-specific headers
    X-UA-Compatible = "IE=edge"
    Vary = "Accept-Encoding, User-Agent"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API function headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, x-farcaster-signature"
    Cache-Control = "no-cache"

# Farcaster well-known files
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

# Handle OPTIONS requests for CORS preflight
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false
  conditions = {Method = ["OPTIONS"]}

# Specific redirects for common API patterns
[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/webhook"
  status = 200