[build]
  command = "vite build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/evermarks/:id"
  to = "/.netlify/functions/evermarks"
  status = 200

[[redirects]]
  from = "/frame/:id"
  to = "/.netlify/functions/frame"
  status = 200

[[redirects]]
  from = "/share/evermark/:id"
  to = "/.netlify/functions/evermark-share"
  status = 200

[[redirects]]
  from = "/api/shares"
  to = "/.netlify/functions/shares"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/shares/*"
  to = "/.netlify/functions/shares"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    X-UA-Compatible = "IE=edge"
    Vary = "Accept-Encoding, User-Agent"

[[headers]]
  for = "/evermark/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://farcaster.xyz https://client.farcaster.xyz https://warpcast.com https://client.warpcast.com https://wrpcd.net https://*.wrpcd.net https://*.thirdweb.com https://*.rpc.thirdweb.com https://c.thirdweb.com https://social.thirdweb.com; frame-ancestors *;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, x-farcaster-signature"
    Cache-Control = "no-cache"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"
    
[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"