[build]
  command = "vite build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# MOBILE-OPTIMIZED HEADERS - REMOVED CSP CONFLICTS
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers (REMOVED CSP to avoid conflicts with HTML)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # MOBILE FRAME SUPPORT - Allow all frame embedding
    # X-Frame-Options removed to avoid conflicts with CSP frame-ancestors
    
    # CORS for mobile webviews
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    
    # Mobile-specific optimizations
    X-UA-Compatible = "IE=edge"
    Vary = "Accept-Encoding, User-Agent"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API function headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, x-farcaster-signature"
    Cache-Control = "no-cache"

# Farcaster well-known files - MOBILE OPTIMIZED
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"
    # Remove frame restrictions for mobile compatibility
    
[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

# Handle OPTIONS requests for CORS preflight
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false
  conditions = {Method = ["OPTIONS"]}

# Specific redirects for common API patterns
[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/webhook"
  status = 200