[build]
  command = "vite build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # SIMPLIFIED CSP - Just what you need for mobile frames
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://mainnet.base.org https://sepolia.base.org https://base-sepolia.g.alchemy.com https://base-sepolia.blockpi.network https://base-sepolia.public.blastapi.io https://rpc.ankr.com https://eth.llamarpc.com https://cloudflare-eth.com https://ethereum.publicnode.com https://api.pinata.cloud https://gateway.pinata.cloud https://ipfs.io https://dweb.link https://*.thirdweb.com https://embedded-wallet.thirdweb.com https://pay.thirdweb.com wss://*.thirdweb.com wss://sepolia.base.org wss://base-sepolia.g.alchemy.com https://*.walletconnect.org wss://*.walletconnect.org https://explorer-api.walletconnect.com https://registry.walletconnect.com https://rpc.walletconnect.com https://*.coinbase.com https://*.metamask.io https://*.farcaster.xyz https://client.farcaster.xyz https://warpcast.com https://client.warpcast.com https://wrpcd.net https://*.wrpcd.net https://privy.farcaster.xyz https://privy.warpcast.com https://auth.privy.io https://*.rpc.privy.systems https://cloudflareinsights.com; img-src 'self' https://gateway.pinata.cloud https://*.pinata.cloud https://ipfs.io https://dweb.link https://*.thirdweb.com https://*.walletconnect.org https://*.coinbase.com https://*.metamask.io data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:; frame-src 'self' https://*.thirdweb.com https://*.walletconnect.org https://*.coinbase.com; worker-src 'self' blob:; child-src 'self' blob:; frame-ancestors 'self' https://*.farcaster.xyz https://warpcast.com https://*.warpcast.com https://fc-iframe.vercel.app https://frames.farcaster.xyz;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "ALLOWALL"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    
[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"